---
language: ruby
cache: bundler
os: linux
before_install: gem install bundler -v 2.1.2
script:
- bundle exec rake rubocop
- bundle exec rake rspec
jobs:
  fast_finish: true
  include:
  - rvm: 2.4.9
  - rvm: 2.5.7
  - rvm: 2.6.5
  - rvm: 2.7.0
  - rvm: ruby-head
  - rvm: jruby-head
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
